name: gnawledge_admin
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.20.2
  meta: ^1.12.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  